<?php

namespace Database\Seeders;

use App\Models\Tour;
use Illuminate\Database\Seeder;

class tourseeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $tours=[
            [
                'name_start_day' => 'پنجشنبه',
                'start_day' => '01/01/25',
                'type_going' => 'هوایی نجف قشم ایر',
                'type_return' => 'برگشت زمینی',
                'type_plan' => '4کربلا-2کاظمین/سامرا-4نجف',
                'type_code' => '2ب ج',
                'price' => '96364488',
                'state' => 'خراسان رضوی',
                'city' => 'مشهد',
                'kargozar' => 'پریان سیر پارسیان',
                'group' => '128',
                'execute_code' => '59523',
                'execute_name' =>'پریان سیر پارسیان',
                'hotel_najaf' => 'ضيوف الامام',
                'hotel_karbala' => 'قصرالضيافه 2',
                'hotel_kazemain' => 'فضوه الشيخ',
                'address' => 'بلوار وکیل آباد، بعد از بلوار جلال آل احمد، نبش وکیل آباد 15، جنب رستوران ملت، پلاک 21',
                'num_days' => '10شب',
            ],
            [
                'name_start_day' => 'پنجشنبه',
                'start_day' => '01/01/25',
                'type_going' => 'هوايي نجف تابان/',
                'type_return' => '',
                'type_plan' => ' 3کربلا-1کاظمین/سامرا-3نجف',
                'type_code' => '2ب ج',
                'price' => '96124188',
                'state' => 'خراسان رضوی',
                'city' => 'مشهد',
                'kargozar' => 'صبح صادق عرفات',
                'group' => '578',
                'execute_code' => '59003',
                'execute_name' =>'صبح صادق عرفات',
                'hotel_najaf' => 'ام القري',
                'hotel_karbala' => 'جبل المروه',
                'hotel_kazemain' => '',
                'address' => 'قصر الکاظميه',
                'num_days' => '7شب',
            ],
            [
                'name_start_day' => 'پنجشنبه',
                'start_day' => '01/01/25',
                'type_going' => 'هوايي نجف تابان',
                'type_return' => '',
                'type_plan' => '3کربلا-1کاظمین/سامرا-3نجف',
                'type_code' => '2ب ج ',
                'price' => '96124188',
                'state' => 'خراسان رضوی',
                'city' => 'مشهد',
                'kargozar' => 'صبح صادق عرفات',
                'group' => '589',
                'execute_code' => '59003',
                'execute_name' =>'صبح صادق عرفات',
                'hotel_najaf' => 'ام القري',
                'hotel_karbala' => 'جبل المروه',
                'hotel_kazemain' => 'قصر الکاظميه',
                'address' => 'خیابان شهید هاشمی نژاد ، بین هاشمی نژاد 25 و 27، پلاک 565 ',
                'num_days' => '7شب',
            ],
            [
                'name_start_day' => 'شنبه',
                'start_day' => '01/01/27',
                'type_going' => ' هوایی نجف تابان',
                'type_return' => '',
                'type_plan' => '3نجف-3کربلا-1کاظمین/سامرا',
                'type_code' => '2الف ب ',
                'price' => '95437438',
                'state' => 'خراسان رضوی',
                'city' => 'مشهد',
                'kargozar' => 'شرکت مرکزی دفاتر خدمات زیارتی خراسان رضوی',
                'group' => '72',
                'execute_code' => '59999',
                'execute_name' =>'شرکت مرکزی دفاتر خدمات زیارتی خراسان رضوی',
                'hotel_najaf' => 'الماس',
                'hotel_karbala' => 'باب الريان',
                'hotel_kazemain' => 'فدک الزهرا',
                'address' => 'مشهد خیابان بهار نبش ملک الشعرا بهار 29 پلاک 4',
                'num_days' => '7شب',
            ],
            [
                'name_start_day' => 'شنبه',
                'start_day' => '01/01/27',
                'type_going' => ' هوایی نجف تابان',
                'type_return' => '',
                'type_plan' => '3نجف-3کربلا-1کاظمین/سامرا',
                'type_code' => '2الف ب',
                'price' => '95437438',
                'state' => 'خراسان رضوی',
                'city' => 'مشهد',
                'kargozar' => 'ستاره شهر بهشت',
                'group' => '140',
                'execute_code' => '59999',
                'execute_name' =>'شرکت مرکزی دفاتر خدمات زیارتی خراسان رضوی',
                'hotel_najaf' => 'الماس',
                'hotel_karbala' => 'باب الريان',
                'hotel_kazemain' => 'فدک الزهرا',
                'address' => 'بلوار مصلی، بین مصلی 21 و 23 ، پلاک 79 ',
                'num_days' => '7شب',
            ],
            [
                'name_start_day' => 'ﺳﻪشنبه',
                'start_day' => '01/01/30',
                'type_going' => 'هوایی نجف تابان',
                'type_return' => '2الف ب',
                'type_plan' => '3نجف-3کربلا-1کاظمین/سامرا',
                'type_code' => '2الف ب',
                'price' => '95437438',
                'state' => 'خراسان رضوی',
                'city' => 'مشهد',
                'kargozar' => 'شرکت مرکزی دفاتر خدمات زیارتی خراسان رضوی',
                'group' => '73',
                'execute_code' => '59999',
                'execute_name' =>'شرکت مرکزی دفاتر خدمات زیارتی خراسان رضوی',
                'hotel_najaf' => 'الماس',
                'hotel_karbala' => 'باب الريان',
                'hotel_kazemain' => 'فدک الزهرا',
                'address' => 'مشهد خیابان بهار نبش ملک الشعرا بهار 29 پلاک 4',
                'num_days' => '7شب',
            ],
            [
                'name_start_day' => 'ﺳﻪشنبه',
                'start_day' => '01/01/30',
                'type_going' => 'هوایی نجف تابان',
                'type_return' => '',
                'type_plan' => '3نجف-3کربلا-1کاظمین/سامرا',
                'type_code' => '2الف ب',
                'price' => '95437438',
                'state' => 'خراسان رضوی',
                'city' => 'مشهد',
                'kargozar' => 'شرکت مرکزی دفاتر خدمات زیارتی خراسان رضوی',
                'group' => '73',
                'execute_code' => '59999',
                'execute_name' =>'شرکت مرکزی دفاتر خدمات زیارتی خراسان رضوی',
                'hotel_najaf' => 'الماس',
                'hotel_karbala' => 'باب الريان',
                'hotel_kazemain' => 'فدک الزهرا',
                'address' => 'مشهد خیابان بهار نبش ملک الشعرا بهار 29 پلاک 4',
                'num_days' => '7شب',
            ],
            [
                'name_start_day' => 'ﺳﻪشنبه',
                'start_day' => '01/01/30',
                'type_going' => ' هوایی نجف تابان',
                'type_return' => '',
                'type_plan' => '3نجف-3کربلا-1کاظمین/سامرا',
                'type_code' => '2الف ب',
                'price' => '95437438',
                'state' => 'خراسان رضوی',
                'city' => 'مشهد',
                'kargozar' => 'راهیان خورشید طوس',
                'group' => '97',
                'execute_code' => '59999',
                'execute_name' =>'شرکت مرکزی دفاتر خدمات زیارتی خراسان رضوی',
                'hotel_najaf' => 'الماس',
                'hotel_karbala' => 'باب الريان',
                'hotel_kazemain' => 'فدک الزهرا',
                'address' => 'خیابان امام خمینی (ره) ، امام خمینی 35 ، پلاک 559 ، طبقه فوقانی پاساژ طاهری ، واحد 2',
                'num_days' => '7شب',
            ],
            [
                'name_start_day' => 'چهارشنبه',
                'start_day' => '01/01/31',
                'type_going' => 'هوایی نجف سپهران',
                'type_return' => '',
                'type_plan' => '3کربلا-1کاظمین/سامرا-3نجف',
                'type_code' => '2الفC',
                'price' => '94299495',
                'state' => 'خراسان رضوی',
                'city' => 'مشهد',
                'kargozar' => 'آتی توس یگانه',
                'group' => '129',
                'execute_code' => '59530',
                'execute_name' =>'آتی توس یگانه',
                'hotel_najaf' => 'قصرالضيافة',
                'hotel_karbala' => 'برج الاماره',
                'hotel_kazemain' => 'خفاجي',
                'address' => 'خیابان احمدآباد ، خیابان ابوذر غفاری ، نبش خیابان ابوذر غفاری 8 ، پلاک 58 ',
                'num_days' => '7شب',
            ],
            [
                'name_start_day' => 'پنجشنبه',
                'start_day' => '01/02/01',
                'type_going' => 'هوايي نجف تابان',
                'type_return' => '',
                'type_plan' => ' 3کربلا-1کاظمین/سامرا-3نجف',
                'type_code' => '2ب ج',
                'price' => '96124188',
                'state' => 'خراسان رضوی',
                'city' => 'مشهد',
                'kargozar' => 'صبح صادق عرفات',
                'group' => '582',
                'execute_code' => '59003',
                'execute_name' =>'صبح صادق عرفات',
                'hotel_najaf' => 'ام القري',
                'hotel_karbala' => 'جبل المروه',
                'hotel_kazemain' => 'قصر الکاظميه',
                'address' => 'خیابان شهید هاشمی نژاد ، بین هاشمی نژاد 25 و 27، پلاک 565',
                'num_days' => '7شب',
            ],
            [
                'name_start_day' => 'پنجشنبه',
                'start_day' => '01/02/01',
                'type_going' => ' هوايي نجف تابان',
                'type_return' => '',
                'type_plan' => '3کربلا-1کاظمین/سامرا-3نجف',
                'type_code' => '2ب ج',
                'price' => '96124188',
                'state' => 'خراسان رضوی',
                'city' => 'مشهد',
                'kargozar' => 'صبح صادق عرفات',
                'group' => '591',
                'execute_code' => '59003',
                'execute_name' =>'صبح صادق عرفات',
                'hotel_najaf' => 'ام القري',
                'hotel_karbala' => 'جبل المروه',
                'hotel_kazemain' => 'قصر الکاظميه',
                'address' => 'خیابان شهید هاشمی نژاد ، بین هاشمی نژاد 25 و 27، پلاک 565',
                'num_days' => '7شب',
            ],
            [
                'name_start_day' => 'شنبه',
                'start_day' => '01/02/03',
                'type_going' => 'هوایی نجف تابان',
                'type_return' => '',
                'type_plan' => '3نجف-3کربلا-1کاظمین/سامرا',
                'type_code' => '2الف ب',
                'price' => '95437438',
                'state' => 'خراسان رضوی',
                'city' => 'مشهد',
                'kargozar' => 'شرکت مرکزی دفاتر خدمات زیارتی خراسان رضوی',
                'group' => '75',
                'execute_code' => '59999',
                'execute_name' =>'شرکت مرکزی دفاتر خدمات زیارتی خراسان رضوی',
                'hotel_najaf' => 'الماس',
                'hotel_karbala' => 'باب الريان',
                'hotel_kazemain' => 'فدک الزهرا',
                'address' => 'مشهد خیابان بهار نبش ملک الشعرا بهار 29 پلاک 4',
                'num_days' => '7شب',
            ],
            [
                'name_start_day' => 'شنبه',
                'start_day' => '01/02/03',
                'type_going' => 'هوایی نجف تابان',
                'type_return' => '',
                'type_plan' => '3نجف-1کاظمین/سامرا-3کربلا',
                'type_code' => '2ج',
                'price' => '94976688',
                'state' => 'خراسان رضوی',
                'city' => 'مشهد',
                'kargozar' => 'صبح صادق عرفات',
                'group' => '596',
                'execute_code' => '59003',
                'execute_name' =>'صبح صادق عرفات',
                'hotel_najaf' => 'ام القري',
                'hotel_karbala' => 'شرق الاوسط',
                'hotel_kazemain' => 'قصر الکاظميه',
                'address' => 'خیابان شهید هاشمی نژاد ، بین هاشمی نژاد 25 و 27، پلاک 565 ',
                'num_days' => '7شب',
            ],
            [
                'name_start_day' => 'یکشنبه',
                'start_day' => '01/02/04',
                'type_going' => ' هوایی نجف قشم ایر',
                'type_return' => 'برگشت زمینی',
                'type_plan' => ' 4کربلا-2کاظمین/سامرا-4نجف',
                'type_code' => '2ب ج',
                'price' => '96364488',
                'state' => 'خراسان رضوی',
                'city' => 'مشهد',
                'kargozar' => 'پریان سیر پارسیان',
                'group' => '126',
                'execute_code' => '59523',
                'execute_name' =>'پریان سیر پارسیان',
                'hotel_najaf' => 'ضيوف الامام',
                'hotel_karbala' => 'قصرالضيافه 2',
                'hotel_kazemain' => 'فضوه الشيخ',
                'address' => 'بلوار وکیل آباد، بعد از بلوار جلال آل احمد، نبش وکیل آباد 15، جنب رستوران ملت، پلاک 21',
                'num_days' => '10شب',
            ],
            [
                'name_start_day' => 'ﺳﻪشنبه',
                'start_day' => '01/02/06',
                'type_going' => 'هوایی نجف تابان',
                'type_return' => '',
                'type_plan' => '3نجف-3کربلا-1کاظمین/سامرا',
                'type_code' => '2الف ب',
                'price' => '95437438',
                'state' => 'خراسان رضوی',
                'city' => 'مشهد',
                'kargozar' => 'شرکت مرکزی دفاتر خدمات زیارتی خراسان رضوی',
                'group' => '74',
                'execute_code' => '59999',
                'execute_name' =>'شرکت مرکزی دفاتر خدمات زیارتی خراسان رضوی',
                'hotel_najaf' => 'الماس',
                'hotel_karbala' => 'باب الريان',
                'hotel_kazemain' => 'فدک الزهرا',
                'address' => 'مشهد خیابان بهار نبش ملک الشعرا بهار 29 پلاک 4',
                'num_days' => '7شب',
            ],
            [
                'name_start_day' => 'چهارشنبه',
                'start_day' => '01/02/07',
                'type_going' => 'هوایی نجف قشم ایر',
                'type_return' => 'برگشت زمینی',
                'type_plan' => '4نجف-4کربلا-2کاظمین/سامرا',
                'type_code' => '2ب ج',
                'price' => '87884488',
                'state' => 'خراسان رضوی',
                'city' => 'مشهد',
                'kargozar' => 'پریان سیر پارسیان',
                'group' => '127',
                'execute_code' => '59523',
                'execute_name' =>'پریان سیر پارسیان',
                'hotel_najaf' => 'ضيوف الامام',
                'hotel_karbala' => 'قصرالضيافه 2',
                'hotel_kazemain' => 'فضوه الشيخ',
                'address' => 'بلوار وکیل آباد، بعد از بلوار جلال آل احمد، نبش وکیل آباد 15، جنب رستوران ملت، پلاک 21',
                'num_days' => '10شب',
            ],
            [
                'name_start_day' => 'پنجشنبه',
                'start_day' => '01/02/08',
                'type_going' => ' هوايي نجف تابان',
                'type_return' => '',
                'type_plan' => ' 3کربلا-1کاظمین/سامرا-3نجف',
                'type_code' => '2ب ج',
                'price' => '96124188',
                'state' => 'خراسان رضوی',
                'city' => 'مشهد',
                'kargozar' => 'صبح صادق عرفات',
                'group' => '584',
                'execute_code' => '59003',
                'execute_name' =>'صبح صادق عرفات',
                'hotel_najaf' => 'ام القري',
                'hotel_karbala' => 'جبل المروه',
                'hotel_kazemain' => 'قصر الکاظميه',
                'address' => 'خیابان شهید هاشمی نژاد ، بین هاشمی نژاد 25 و 27، پلاک 565 ',
                'num_days' => '7شب',
            ],
            [
                'name_start_day' => 'شنبه',
                'start_day' => '01/02/10',
                'type_going' => 'هوایی نجف تابان',
                'type_return' => '',
                'type_plan' => '3نجف-3کربلا-1کاظمین/سامرا',
                'type_code' => '2الف ب ',
                'price' => '95437438',
                'state' => 'خراسان رضوی',
                'city' => 'مشهد',
                'kargozar' => 'آبتین سیر توس',
                'group' => '25',
                'execute_code' => '59999',
                'execute_name' =>'شرکت مرکزی دفاتر خدمات زیارتی خراسان رضوی',
                'hotel_najaf' => 'الماس',
                'hotel_karbala' => 'باب الريان',
                'hotel_kazemain' => 'فدک الزهرا',
                'address' => 'بلوار سجاد، خیابان بزرگمهر جنوبی، بین بزرگمهر جنوبی 9 و 11، پلاک 175',
                'num_days' => '7شب',
            ],
            [
                'name_start_day' => 'شنبه',
                'start_day' => '01/02/10',
                'type_going' => 'هوایی نجف تابان',
                'type_return' => '',
                'type_plan' => '3نجف-3کربلا-1کاظمین/سامرا',
                'type_code' => '2الف ب',
                'price' => '95437438',
                'state' => 'خراسان رضوی',
                'city' => 'مشهد',
                'kargozar' => 'شرکت مرکزی دفاتر خدمات زیارتی خراسان رضوی',
                'group' => '76',
                'execute_code' => '59999',
                'execute_name' =>'شرکت مرکزی دفاتر خدمات زیارتی خراسان رضوی',
                'hotel_najaf' => 'الماس',
                'hotel_karbala' => 'باب الريان',
                'hotel_kazemain' => 'فدک الزهرا',
                'address' => 'مشهد خیابان بهار نبش ملک الشعرا بهار 29 پلاک 4',
                'num_days' => '7شب',
            ],
            [
                'name_start_day' => 'شنبه',
                'start_day' => '01/02/10',
                'type_going' => ' هوایی نجف تابان',
                'type_return' => '',
                'type_plan' => '3نجف-1کاظمین/سامرا-3کربلا',
                'type_code' => '2ج',
                'price' => '94976688',
                'state' => 'خراسان رضوی',
                'city' => 'مشهد',
                'kargozar' => 'صبح صادق عرفات',
                'group' => '598',
                'execute_code' => '59003',
                'execute_name' =>'صبح صادق عرفات',
                'hotel_najaf' => 'ام القري',
                'hotel_karbala' => 'شرق الاوسط',
                'hotel_kazemain' => 'قصر الکاظميه',
                'address' => 'خیابان شهید هاشمی نژاد ، بین هاشمی نژاد 25 و 27، پلاک 565 ',
                'num_days' => '7شب',
            ],
         ];

         foreach($tours as $tour)
         {
            Tour::create([
                'name_start_day' => $tour['name_start_day'],
                'start_day' => $tour['start_day'],
                'type_going' => $tour['type_going'],
                'type_return' => $tour['type_return'],
                'type_plan' =>$tour['type_plan'],
                'type_code' => $tour['type_code'],
                'price' => $tour['price'],
                'state' => $tour['state'],
                'city' => $tour['city'],
                'kargozar' => $tour['kargozar'],
                'group' => $tour['group'],
                'execute_code' => $tour['execute_code'],
                'execute_name' =>$tour['execute_name'],
                'hotel_najaf' => $tour['hotel_najaf'],
                'hotel_karbala' => $tour['hotel_karbala'],
                'hotel_kazemain' => $tour['hotel_kazemain'],
                'address' => $tour['address'],
                'num_days' => $tour['num_days'],
            ]);
         }
    }
}
